all:ejercicio2

clean: 
	rm ejercicio2 ResultadoElecciones.txt
	echo "--Se ha eliminado el ejecutable de ejercicio2--"
	echo "--Se ha eliminado el documento ResultadoElecciones.txt--"

ejercicio2: ejercicio2.cpp
	g++ -o ejercicio2 ejercicio2.cpp
	

